package.json, src/components/alerting.tsx, src/components/silence-form.tsx, src/components/utils.ts, yarn.lock
Without this fix, the UI does not update to reflect the changes made until the next poll of the silences API.
Also upgrades `dynamic-plugin-sdk` to v0.0.18 to fix a type error with the `Silence` type introduced by this change.
=> Fix silences data update after creating, editing or expiring a silence

package.json, yarn.lock
Also add to yarn "resolutions" because otherwise the console dynamic SDK causes v5.74 to also be used.
=> Upgrade webpack to ^5.76.0

locales/en/public.json, src/components/_monitoring.scss, src/components/alerting.tsx
Adds the ability to bulk expire silences from the silences list page.
Adds a checkbox per row to the silences list for selecting silences as well as a checkbox for selecting / unselecting all of the silences.
If the list is currently filtered, the select all checkbox only selects the currently displayed silences, but unselecting all also unselects any silences that are currently hidden.
=> OU-158: Add bulk expire for silences

src/components/alerting.tsx
This bug was normally not seen because after expiring the silences, they are not displayed on the list page with the default list settings. You could see the bug by changing the list filter to display the expired silences before navigating away from the page.
=> After bulk expiring silences, the silences should be deselected

src/components/alerting.tsx
If all of the currently visible silences are already expired, disable the checkbox for selecting all silences.
This is better UX because we disable each silence's individual checkbox if it is expired and we should be consistent with that. If in the future we add a bulk action for expired silences, we can change this behavior.
=> Disable select all silences checkbox if all silences are expired

src/components/query-browser.tsx
This prop was already removed in the web console codebase by https://github.com/openshift/console/pull/12464, so it should also be removed here.
=> Remove unused wrapperClassName prop from QueryBrowser

console-extensions.json
This PR adjusts the extensions to match the original ones that consider flags to hide or show the observe menu and submenus: https://github.com/openshift/console/blob/master/frontend/packages/console-app/console-extensions.json#L1261
It also adds i18n files to provide translations for the menu items, taken from: https://github.com/openshift/console/tree/master/frontend/packages/console-app/locales
=> Improve console extensions including flags

src/components/alerting.tsx
Calling `i18next.t()` is not reliable, so always use `useTranslation`
=> Fix some translations

console-extensions.json
This fixes a bug where plugin interferes with the Alertmanager config pages, which also live under monitoring/
=> Fix so that plugin only handles specific pages under monitoring/

.eslintrc.yml, src/components/alerting.tsx, src/components/dashboards/index.tsx, src/components/dashboards/single-stat.tsx, src/components/dashboards/table.tsx, src/components/dashboards/timespan-dropdown.tsx, src/components/dashboards/useFetchDashboards.ts, src/components/hooks/useIsVisible.ts, src/components/metrics.tsx, src/components/promql-expression-input.tsx, src/components/query-browser.tsx, src/components/targets.tsx
Also changes the eslint `ecmaVersion` to `2018` although this doesn't require any code changes.
These changes align us with the web console code changes made by https://github.com/openshift/console/pull/12821
=> Enable react-hooks/exhaustive-deps eslint rule

package.json, yarn.lock
Matches the version now used by the OpenShift web console
=> Upgrade React Router to 5.3.x

.eslintrc.yml, src/components/alerting.tsx, src/components/console/console-shared/error/error-boundary.tsx, src/components/console/extensions/types.ts, src/components/console/utils/status-box.tsx, src/components/dashboards/index.tsx, src/components/metrics.tsx, src/components/query-browser.tsx, src/components/silence-form.tsx, src/components/targets.tsx
Remove some uses of `{}` that don't actually make any difference to the type check being done.
=> Enable `@typescript-eslint/ban-types` eslint rule

src/components/alerting.tsx
These checkboxes don't do anything on this page. They are only used on the main Silences list page.
=> OU-230: Remove checkboxes from the Silenced By list on alert details page

console-extensions.json
Fix redirect from `/monitoring` to `/monitoring/alerts` and from `/monitoring/graph` to `/monitoring/query-browser`.
The redirects are implemented by the `MonitoringUI` component, but they were missing from `console-extensions.json`, so were never getting to `MonitoringUI`.
=> OCPBUGS-17650: Fix /monitoring/ redirects

src/components/dashboards/index.tsx
Changing the selected value for one variable dropdown can cause the available options for other variable dropdowns to be updated. In this case, those options would sometimes fail to update.
The bug seems to be caused by the PatternFly <Select /> not rerendering the component under certain circumstances. Rendering the select options inline works around the problem.
=> OCPBUGS-7184: Fix bug where the variable dropdown options were not updated

console-extensions.json
This reverts commit 0f32328ddad72c1ffaa4820f3f4359362a9d1acf (PR https://github.com/openshift/monitoring-plugin/pull/73)
=> Revert "Fix i18n namespace for navigation menu entries"

src/components/utils.ts
[OU-179](https://issues.redhat.com//browse/OU-179) Display externalLabels found in GET `/api/prometheus/api/v1/rules` response >> `rules.labels`.
**Related Issue:** 
https://issues.redhat.com/browse/OU-179
**AlertDetailsPage**
External labels are now listed alongside the other labels associated with an alert.
**Search Label** 
The external labels can be pre-populated in the 'label' search field. 
**Silences**
We're able to silence alerts associated with the external label. 
**To Test:** 
1. Attach an externalLabel to all time-series and alerts leaving the Prometheus instance that monitors core OpenShift Container Platform projects [[docs]](https://docs.openshift.com/container-platform/4.13/monitoring/configuring-the-monitoring-stack.html#attaching-additional-labels-to-your-time-series-and- …
=> OU-179: Fix the root cause of externalLabels not present on alerts

src/components/silence-form.tsx
| Before | After|
| - | - |
| ![before](https://github.com/openshift/monitoring-plugin/assets/460802/b4d05373-cace-4340-96d0-963deac5a7f3) | ![after](https://github.com/openshift/monitoring-plugin/assets/460802/72ea0712-7462-4210-ad9c-5b34452ae3af) |
FYI @fkargbo
=> OU-261: Fix "Overwriting current silence" info alert to have padding

Dockerfile, README.md
This PR fixes the path the `ubi8/nginx-120` uses to look for files
=> OU-298: fix default nginx path to look for static files

console-extensions.json
The 4.15 console version includes an upgrade to use react router v6 in compatibility mode with v5. In react router v6 regex paths are not longer supported as seen [here](https://reactrouter.com/en/main/start/faq#what-happened-to-regexp-routes-paths). 
This PR splits the regex into multiple console routes so the route can be matched correctly and the pages are visible
=> OCPBUGS-24515: remove regex from console page route path so plugin pages are found

console-extensions.json
=> OCPBUGS-24658: remove regex from console page route path so plugin pages are found

src/components/alerting.tsx
Before this change we required all of the alert's labels to be in the URL query params. This change allows the alert to be shown even if only some of its labels are in the URL, as long as there is only one such matching alert.
Fixes a bug where the alerts links in "Notifications" didn't work because they didn't include the alert's external labels.
=> OCPBUGS-25313: On the alert details page, don't require all alert labels in URL

Dockerfile, README.md
This change should only have been made for building images for local testing, not in the default `Dockerfile`.
This reverts PR https://github.com/openshift/monitoring-plugin/pull/83 and commit 4965ae66e6fa6ed9860e4b931bf7590be7c9a880.
=> OU-308: Revert "fix default nginx path to look for static files"

package.json, yarn.lock
Upgrade follow-redirects parent dependencies to a safe version
=> OCPBUGS-27201: upgrade follow-redirects parent dependency

src/components/dashboards/table.tsx
In order to display all results from a vector response in the dashboards table, this PR calculates table rows considering all the metric labels
=> OU-309: consider all metric keys to display all results on dashboards tables

yarn.lock
Upgrades Webpack dev server.
This also upgrades follow-redirects transitive dependency, addressing [OCPBUGS-30934](https://issues.redhat.com/browse/OCPBUGS-30934)
=> OCPBUGS-31291: Upgrade Webpack dev server

package.json, yarn.lock
This PR upgrade sanitize-html vulnerable dependency
=> OCPBUGS-29947: upgrade sanitize-html vulnerable dependency

src/components/console/graphs/helpers.ts, src/components/dashboards/index.tsx, src/components/query-browser.tsx, src/components/types.ts, src/components/utils.ts
**Issue:** https://issues.redhat.com/browse/OU-370
Queries with a duration of more than 2 days will time out for certain dashboards due to the large time period of data being queried and the density of the data for those queries. Since we know that the shorter queries don't time out, we can split the larger queries time periods down into durations that won't time out (1 day), and then recombine all the returned data.
However, we can only recombine query types which isn't dependent on other dimensions (labels) or that which is directly dependent on time (line charts). 
The labels query uses a set to keep track of all options for the label across the split queries. The query-browser (line chart) breaks the query down into its needed time chunks, then looks to recombine the data into the …
=> OU-370: Split Dashboard Label and Line Chart Queries

locales/en/plugin__monitoring-plugin.json, src/components/dashboards/index.tsx, src/components/metrics.tsx
This PR:
- Adds support for metrics to fetch data from a custom datasource registered using the console-dashboards-plugin
- Adds a `datasource` URL param with the name of the custom datasource, so when clicking on a dashboards that contains a custom datasource the metrics are loaded form the correct backend
=> OU-379: Add datasource parameter to handle metrics from custom datasources

src/components/silence-form.tsx
The API for getting the current user changed on 4.15. This PR fixes the auto filling and marks the field as mandatory
=> OCPBUGS-31931: make createdBy mandatory and auto fill with the current user

src/components/alerting.tsx
In the screenshot below the see related logs is a link and the troubleshoot is a button, both with same styling for consistency.
=> OU-395: Alert detail page renders buttons and links from the plugin extension

Dockerfile
Recently, we added OKD configs for openshift components - [this](https://github.com/openshift/release/blob/master/ci-operator/config/openshift/monitoring-plugin/openshift-monitoring-plugin-main__okd-scos.yaml) is the OKD config for the monitoring plugin component. The config overrides the base image with a centos image, which doesn't work because the base image for the `Dockerfile` is an nginx image. To be consistent with other repos and the ART dockerfile, change the nginx base image to a rhel base image, so that prow can do the substitution. This also prevents any CVE vulnerabilities we would have when using the nginx image.
=> OKD-210: Use rhel9 base image in Dockerfile

console-extensions.json, src/actions/observe.ts, src/components/alerting.tsx, src/components/alerting/AlertUtils.tsx, src/components/alerting/AlertsPage.tsx, src/components/alerting/README.md, src/components/console/console-shared/hooks/useActiveNamespace.ts, src/components/dashboards/custom-time-range-modal.tsx, src/components/dashboards/graph.tsx, src/components/dashboards/index.tsx, src/components/dashboards/monitoring-dashboard-utils.ts, src/components/dashboards/timespan-dropdown.tsx, src/components/dashboards/types.ts, src/components/fetch-alerts.tsx, src/components/hooks/usePerspective.tsx, src/components/silence-form.tsx, src/components/utils.ts
This PR is apart of a pair of PR's (along with [this](https://github.com/openshift/console/pull/14014) one in the console codebase) which look to move the alerting list page from the console codebase over to the monitoring one. This PR needs to merge before the PR in the console codebase can merge. I would further prefer if both could be merged at the same time, by receiving approval on both before either merges.
There is a good amount of code that has changed and a good amount that has been split into other files. While reviewing the code, if you get lost then feel free to take a look at the different commits for this PR, as they are grouped by what they do. Once this PR is approved I will squash them all down, and then re-request approval.
This PR changes the UI of the developer …
=> OU-251: Migrate Developer Perspective Alert List to Monitoring Plugin

src/components/alerting.tsx, src/components/utils.ts
The monitoring-plugin adds the labels from the rules onto the individual alerts, which causes the dev details page to fail to match the labels from the alert (which are encoded into the url) and then says alert not found.
This PR prevents the rule labels from being added to the alert labels in the developer persepctive.
=> OU-251: Prevent rule labels from being added to alert labels for dev console

src/components/alerting.tsx
Since the namespace variable is what determines whether the tenancy URL or the admin URL is used in the `getPrometheusURL` we should ensure that it only gets passed in when being called in the dev perspective.
=> OCPBUGS-36970: Use the non-tenancy URL in the Admin perspective

console-extensions.json, src/components/alerting.tsx, src/components/metrics.tsx, src/components/query-browser.tsx
**Description:**
This PR aims to consolidate code so that the Administrator and Developer perspectives render the same UI, which the monitoring plugin will serve.
This PR removes the files associated with the Dev Perspective > Observe > Metrics page. The monitoring plugin will now serve this page, PR for this is https://github.com/openshift/console/pull/14105 .
**Related JIRA Issues**
[CONSOLE-4187](https://issues.redhat.com/browse/CONSOLE-4187) : Dev console: Use Metrics page from monitoring-plugin
[OU-258](https://issues.redhat.com/browse/OU-258): Dev console: Use Metrics page from monitoring-plugin
These are duplicate issues because the openshift/console requires the PR title to be associated with an OCP-owned JIRA issue.
**Tandem PR: openshift/console PR#14105**
[openshift/console …
=> OU-258: Dev console: Use Metrics page from monitoring-plugin

Dockerfile.art
This PR fixes the image used from the ART team , including the right target folder
=> NO-JIRA: fix cachito target folder

Dockerfile
The okd-scos image in 4.17 being used doesn't have access to microdnf. This PR adds a slightly heavier image, but one that has access to dnf to install the needed dependencies.
Testing for this PR on the 4.17 branch is being done here in #153
=> NO-JIRA: Use DNF and go based image in Dockerfile

web/package.json, web/src/components/alerting/AlertsPage.tsx, web/yarn.lock
Formats Alert data into comma-separated values string and passes it to <VirtualizedTable> so it can be exported. 
https://github.com/user-attachments/assets/4064daf3-59c3-4b9e-9aff-0f5d964d9a07
<b>HOLD</b>: The changes needed for the Virtualized table to support an export CSV button is found here:   https://github.com/openshift/console/pull/14050. We are awaiting the merge/release of the feature. Then, we can upgrade the monitoring-plugin's `package.json` .
=> OU-431: Export CSV for Alert Tables

web/src/components/alerting.tsx, web/src/components/alerting/AlertsPage.tsx, web/src/components/console/utils/status-box.tsx
This PR updates the empty pages of alerts listers to use the resource labels to provide more information.
<details>
<summary>Previous UIs</summary>
</details>
<details>
<summary>New UIs</summary>
</details>
The developer perspective silences page hasn't been updated with this change since it is still located in the `openshift/console` codebase. Once the silence UI is brought over it will have the same changes.
=> OCPBUGS-36921: Use resource label when showing empty alert list pages

web/console-extensions.json
Update `console-extension.json` to use translations from `openshift/monitoring-plugin/.../plugin__monitoring-plugin.json` instead of `openshift/console/.../public.json`
=> OU-259: Update console-extension to use translations in plugin__monitoring-plugin

cmd/plugin-backend.go
`opt/app-root/web/dist` isn't a valid path, while `/opt/app-root/web/dist` is.
=> NO-JIRA: Fix default paths for go-server

Dockerfile.art, Dockerfile.ci, Dockerfile.local
This PR looks to remove the backwards compatibility of the `monitoring-plugin` images and instead use the go backend
=> OU-450: Use plugin-backend as default ENTRYPOINT

README.md, cmd/plugin-backend.go, pkg/server.go
Due to the addition of a health check on the monitoring plugin deployment, the `/health` endpoint is getting hit quite often, leading to an excessive amount of logs being generated. This is also true for other endpoints as well, such as the `/plugin-manifest.json` which is polled around every 15 seconds per user logged into the console.
This PR looks to combat these excessive logs by not logging individual requests when an endpoint is hit, unless a new `log-verbosity` parameter is set to 1.
=> OCPBUGS-41602: Reduce default logging

src/components/Incidents/IncidentsPage.jsx, src/components/Incidents/utils.js
1. Set up matcher function so it could provide label numbers for filter dropdown
2. I refactored the processIncidentTimestamps a bit so it could assign boolean values correctly
In the next PR I will look into refactoring filterIncident function so I could utilize these boolean values for filtering and avoid doing double filtering
=> incidents-filter-matcher

src/components/Incidents/IncidentsPage.jsx, src/components/Incidents/utils.js
Updated incidents filter to allow multiple selections and removed parts of the code that were moved to the processIncidentsTimestamps function (I renamed it to processIncidents because it does more than timestamps processing now)
=> update incidents filter to allow multiple selected options

web/src/components/SimpleSelect.tsx, web/src/components/dropdown-poll-interval.tsx, web/src/components/metrics.tsx
[OCPBUGS-42851](https://issues.redhat.com/browse/OCPBUGS-42851) Refresh interval button on "Observe -> Metrics" page failed to load for admin/developer console
Figure 1. Runtime Error produced by bug. 
Figure 2. Admin > Observe > Metrics > Interval Dropdown is not functional. 
Figure 3. Dev > Observe > Metrics > Interval Dropdown is not functional. 
Figure 4. Admin > Observe > Metrics > Interval Dropdown is replaced with a functional dropdown. 
Figure 5. Admin > Observe > Metrics > Interval Dropdown is replaced with a functional dropdown.
=> OCPBUGS-42851: Refresh interval button on "Observe -> Metrics" page failed to load for admin/developer console

web/package.json, web/yarn.lock
This PR 
- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly
This PR is done directly to `release-4.17` as the dependency does not exists anymore in 4.18
=> OCPBUGS-43238: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.17

package.json, yarn.lock
This PR
- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly
This PR is done directly to release-4.16 as the sdk dependency support varies for 4.16
=> OCPBUGS-43239: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.16

web/src/components/alerting/AlertsPage.tsx
This PR looks to fix an issue which was discovered in ACM Alerting, but also present in the primary monitoring-plugin which creates bad formatting within the kebab dropdown on the alerts page.
This issue stems from the change to using the Patternfly 5 deprecated components for the Dropdown, while missing some of the Patternfly 4 DropdownItems which should also have been migrated.
Before: 
After:
=> COO-493: Fix alerts page kebab dropdown

package.json, yarn.lock
This PR
- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly
This PR is done directly to release-4.15 as the sdk dependency support varies for 4.15
=> OCPBUGS-43242: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.15

package.json, yarn.lock
This PR
- updates the dynamic plugin sdk to remove vulnerable dependencies
- updates other vulnerable dependencies directly
This PR is done directly to release-4.14 as the sdk dependency support varies for 4.14
=> OCPBUGS-43243: upgrade dynamic plugin sdk to remove vulnerable dependencies 4.14

web/console-extensions.json, web/src/components/alerting.tsx, web/src/components/alerting/AlertsDetailPage.tsx, web/src/components/alerting/SilencesPage.tsx, web/src/components/silence-form.tsx, web/src/components/utils.ts
https://issues.redhat.com/browse/OU-257
https://issues.redhat.com/browse/CONSOLE-4330
This duplicate issue was created because openshift/console github bots require a valid CONSOLE Jira to be associated with all PRs. 
https://github.com/openshift/console/pull/14480
To consolidate the code of the` Developer View > Observe > Silences Tab` is being moved from `openshift/console` to `openshift/monitoring-plugin`.
- This PR renders the 'Silences' tab in the openshift/monitoring-plugin. 
- The corresponding [PR](https://github.com/openshift/console/pull/14480) removes the 'Silences' tab in the openshift/console. 
- This PR should be tested with https://github.com/openshift/console/pull/14480
- All functionalities should be the same as before. No new features were added.
=> OU-257: Migrate Developer View > Observe > Silences Tab from openshift/console to openshift/monitoring-plugin

web/console-extensions.json
This pr removes the incidents extensions from the default extensions as it should be loaded only when enabling the `incidents` feature
=> NO-JIRA: remove incidents from default extensions

Dockerfile.mcp, Makefile, README.md, pkg/server.go, scripts/build-image.sh, scripts/deploy-acm.sh
This PR looks to decouple the monitoring-console-plugin information and scripts from the acm-alerting feature
=> NO-JIRA: Update readme and deployment scripts

web/src/reducers/observe.ts
Don't try to set the notificationAlerts.data until it has been initialized. 
Bug is able to be reproduced when refreshing the alerting page or opening the alerting page in a new tab.
=> OCPBUGS-44447: Don't set property on undefined variable

config/incidents.patch.json, web/console-extensions.json, web/package.json, web/src/components/Incidents/IncidentsPage.jsx, web/src/components/alerting.tsx, web/src/components/hooks/useFeatures.ts
This PR looks to fix the extension points used by the incidents tab.
It no longer places incidents as a tab under Alerting, but instead as a new Tab under Observe.
It also removes the monitoring-plugin reducer from the CMO deployment, as the CMO reducer interferes with the creation of the incidents state in the plugin store.
Finally, it prevents the validation of the console-extension.json file during build in the package.json, as the validation doesn't allow for exposed modules without them being used. However, we need to do this, so that the extension patches can have access to things that the monitoring-plugin doesn't need.
=> OU-584: Fix issues preventing the incidents tab from showing

web/src/components/Incidents/IncidentsDetailsRowTable.jsx, web/src/components/Incidents/IncidentsTable.jsx, web/src/components/Incidents/api.js, web/src/components/Incidents/processAlerts.js
https://issues.redhat.com/browse/RHINENG-14523
1) Updated sample resolution to 288 per day, which allows us to see data from incidents much faster ~10 minutes now
2)  Updated logic that gathers rows for expanded details table. If, for some reason, there is no rule matching the alert name -> we disable the link to that rule + add a tooltip with helper text. We disable kebab actions as well.
3)Updated logic that renders firing/resolved icon in expanded details
4)Updated logic that gathers components for the main table. Now, it has an additional step - it reads the alerts assigned to the "component" and checks their "alertstate", if at least 1 alert has a firing status -> the component will have a firing status. If all of the alerts assigned to the "component" are resolved -> the component …
=> RHINENG-14523: Fix expanded row won't render without rule details + firing logic update

scripts/start-console.sh, web/src/components/cancellable-fetch.ts, web/src/components/dashboards/index.tsx, web/src/components/dashboards/perses-client.ts, web/src/components/dashboards/usePerses.ts
On the dashboard page, list [Perses](https://github.com/perses/perses) dashboards in the dropdown. 
This PR only lists the dashboards in the dropdown; the dashboard is not rendered when you click on the dropdown item. 
**Figure 1.** Perses dashboards are listed in the dashboard page dropdown  (e.g., "testproject / dashboard1" and "testproject / dashboard2"). The dashboards are displayed as <"project name"> / <"dashboard name">. The tag, by default, is "perses."
https://issues.redhat.com/browse/OU-432
This PR was only tested locally during development. To setup the test: 
1. Launch a perses container `docker run --name perses -d -p 127.0.0.1:8080:8080 persesdev/perses`. See https://github.com/perses/perses?tab=readme-ov-file#docker-images for information. 
2. Navigate to …
=> OU-432: Merge Perses dashboards with current dashboards list 

web/src/components/silence-form.tsx
This PR looks to bring the fix added in openshift/console#13926 to the monitoring plugin. As correctly predicted by @kyoto [here](https://github.com/openshift/console/pull/13926#issuecomment-2151200540) now that we have moved from Patternfly 4 to 5, this fix is needed in the monitoring-plugin as well.
=> OCPBUGS-45801: Allow editing the until field on the silence edit page

web/src/components/console/graphs/bar.tsx
This PR looks to solve an issue which led the length of an individual bar on a bar chart to exceed the bounds of the bar chart. 
Before: 
After:
Minimum Dashboard Reproduction:
<details>
<summary><b>Minimum Dashboard Reproduction</b></summary>
```yaml
kind: ConfigMap
apiVersion: v1
metadata:
labels:
console.openshift.io/dashboard: 'true'
console.openshift.io/odc-dashboard: 'true'
name: world-dashboard
namespace: openshift-config-managed
data:
etcd.json: |-
{
"description": "Test Dashboard to load in the hello world metric",
"editable": true,
"gnetId": null,
"hideControls": false,
"refresh": "10s",
"panels": [
{
"targets": [
{
"expr": "sum(rate(container_network_receive_bytes_total[1m])) by (node)"
}
],
"title": "title",
"type": "grafana-piechart-panel"
}
]
}
```
</details>
=> OCPBUGS-45174: Fix bounds on bar chart

web/webpack.config.ts
We use some scripts to run monitoring plugin in a different port sometimes. 
It would be cool to have this env in the configuration so we don't have to manually edit the code locally.
=> NO-JIRA: Run webpack with a different port

web/src/components/query-browser.tsx
When retrieving the prometheus URL to query, the embedded query-browser was using the passed in namespace in the admin console (which can exist) when it should instead not be passing in any namespace, as the query will go against the whole cluster not a specific namespace
=> OCPBUGS-45896: Fix admin console alert detail graph

web/src/components/alerting/AlertUtils.tsx, web/src/components/dashboards/graph.tsx, web/src/components/query-browser.tsx
/hold Until #288 is merged
Clean up some tech debt when we are passing the namespace into the component as a prop, but the useActiveNamespace is already called.
=> NO-JIRA: Remove duplicate parameter

config/incidents.patch.json, scripts/start-console.sh, web/src/components/alerting.tsx, web/src/components/hooks/useFeatures.ts, web/src/components/hooks/usePerspective.tsx
https://issues.redhat.com/browse/OU-588
- Relocate the Incidents tab from Observe > Incidents to Observe > Alerting > Incidents tab. 
- the frontend use a proxy `/api/proxy/plugin/monitoring-console-plugin/backend/features` to fetch the list of features enabled from the golang [backend](https://github.com/openshift/monitoring-plugin/blob/1d2e50f162df985768a7faaa2e6f47740bfb87a6/pkg/server.go#L185). Cluster Observability Operator configures the proxy [here](https://github.com/rhobs/observability-operator/blob/28ac1ba9e179d25cae60e8223bcf61816e23a311/pkg/controllers/uiplugin/monitoring.go#L44).
This is an initial solution. The [long-term solution](https://issues.redhat.com/browse/OU-625) is to modify the openshift/console-dynamic-plugin-sdk > …
=> OU-588: Move Incidents Tab to Alerting Page 

web/src/components/alerting/SilencesDetailPage.tsx
Fixes an issue which prevented the namespace from being populated in the alert URL located in the silences page.
This was due to the namespace not being passed in to the URL generator function
=> OCPBUGS-48142: Fix Dev Perspective Alert URL namespace

web/src/components/Incidents/IncidentsPage.jsx, web/src/components/Incidents/processAlerts.js, web/src/components/Incidents/processIncidents.ts
https://issues.redhat.com/browse/RHINENG-15362
Sort the bars in the charts based on their first timestamp
=> RHINENG-15362: Sort the bars in the charts based on their first timestamp

web/src/components/Incidents/AlertsChart/AlertsChart.jsx, web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx, web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx, web/src/components/Incidents/IncidentsPage.jsx, web/src/components/Incidents/IncidentsTable.jsx, web/src/components/Incidents/consts.js, web/src/components/Incidents/utils.js
The issue https://issues.redhat.com/browse/OU-628
This PR fixes 2 major things:
1) I updated the logic for creating bars for the alert chart. Now the bar respects the gaps in time and the bars are created accordingly and not smushed all together into 1 line
2) I added more logic to how we manage loading states for the alerts chart and incidents table. Now if the date changes -> we force loading states so the component won't render BEFORE we get new data from the API. Previously there was an issue that was causing the component to render again with old data, without waiting for the API calls to resolve.
Smaller things I added in this PR:
I added unselect logic to the "onclick" function that fires when the user clicks on an incident in the incident chart.
I replaced the PF color variables …
=> RHINENG-15284: Sync alerts chart and incidents table with days filter

web/src/components/alerting.tsx, web/src/components/hooks/usePerspective.tsx
During the last rebase and merge a number of small issues cropped up with the virtualization perspective routes and routing which makes them generally unsynced. This PR looks to bring them back in line. 
Virtualization perspectives after these changes can be seen [here](https://drive.google.com/file/d/1aTznX2F82wUVBJOqkdV1DqMDt0eAmLwc/view?usp=sharing).
This PR should be merged before #306 to prevent issues with backporting to 4.18.
=> OU-645: Fix virtualization perspective routes and routing

web/src/components/Incidents/AlertsChart/AlertsChart.jsx, web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx, web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx, web/src/components/Incidents/IncidentsPage.jsx, web/src/components/Incidents/utils.js
Dark theme support for incidents page:
1) added hook made by Andreas for other openshift project https://github.com/openshift/distributed-tracing-console-plugin/commit/38dae4c768d9ac3cb03bffa8e06d2224f4515bea
2)Pass theme value to the charts and calculate the following things:
1. Color of chart bars for all 3 types
2. Text of axis
3. Text of legend
4. Legend's color
Also, I updated the logic for the OnClick functionality in the Incidents chart.  Now, we use fillOpacity props instead of using switch-case and fill props.
=> RHINENG-15582: Incidents dark theme support

web/src/components/Incidents/processIncidents.ts, web/src/components/Incidents/utils.js
1) The old logic for processing severity was dependent on src_severity, it is unreliable. With how we combine incidents into 1 object depending on group id the src_severity could be "warning" even though there are timestamps with "2" in the second index which marks 'critical'. I updated the logic to mark the incident as critical/warning/info if we have at least 1 timestamp with critical/warning/info. 
2)Updated filter logic to make sure that long standing is Additive. That means by default we return everything except long standing
=> RHINENG-15501: Fixing incidents filter issues with severeties and long standing

web/src/components/Incidents/IncidentsDetailsRowTable.jsx, web/src/components/Incidents/processAlerts.js
https://issues.redhat.com/browse/RHINENG-15594
1) fixed the logic of how we add the "alertsEndFiring" prop, previously, the values were not sorted, so it could differ from the actual last timestamp. Now it properly assigns it.
2) Improved logic of when we add the tooltip to the Link in the alert expanded details in the table. Now if we don't have rule OR if the alert is resolved -> we make the link non clickable and add a tooltip with helper text.
=> RHINENG-15594: fix tooltip in row details

web/src/components/Incidents/IncidentsPage.jsx, web/src/components/Incidents/processAlerts.js
Due to the limitations of how the API works when we request alerts data we can "catch" alerts data for the other incidents. Specifically the time before/after the chosen/selected incident starts/ends. To avoid showing this data I need to introduce a cut-off time, and make sure we're not showing alerts for the time when the chosen incident is not "happening"
Before
After
=> rhineng-16008: add cutoff for alerts timestamps

web/src/components/Incidents/IncidentsPage.jsx
This PR looks to add a header for the incidents page.
=> NO-JIRA: add incidents header

web/src/components/dashboards/perses/PersesWrapper.tsx, web/src/components/dashboards/perses/datasource-api.ts, web/src/components/dashboards/perses/perses-client.ts, web/src/components/dashboards/perses/perses/datasource-api.ts
This PR, adds the plugin proxy path before the perses proxy so requests to datasources are proxied correctly
=> COO-768: add plugin proxy to perses proxy path

web/src/components/hooks/useRulesAlertsPoller.ts
This PR looks to fix an issue with didn't add the external labels to the alerts in the admin perspective in 4.17.
This caused links with the external labels from correctly linking to the appropriate pages. The parameter for the `getAlertsAndRules` function is `isAdminPerspective`, while we were passing in `isDev`.
=> [release-4.17] OCPBUGS-51117: Fix overview links

web/src/components/alerting/AlertRulesDetailsPage.tsx, web/src/components/alerting/AlertUtils.tsx
Don't show metrics links in the acm perspective since the metrics page isn't present
=> OU-700: don't show metrics links in acm perspective

web/src/components/metrics.tsx
JIRA 
https://issues.redhat.com/browse/OCPBUGS-52592
`const isSpan = (item) => item?.title?.props?.children;`
The optional chaining operator `?.` gracefully handles undefined `item` by not throwing errors and allowing `item?.title?.props?.children` to result as `undefined`.
=> OCPBUGS-52592: Fix "Export as CSV"

web/src/components/alerting.tsx, web/src/components/alerting/AlertsDetailPage.tsx, web/src/components/alerting/AlertsPage.tsx, web/src/components/hooks/useSilencesPoller.ts, web/src/components/silence-form.tsx
The alerts were actually being fetched correctly. However the silences state was being pulled from the admin perspective state store, which was failing (correctly) to poll the non-tenancy API for the notification bell. In addition, the silences poller wasn't being called on all pages that needed it.
The tenancy API is not returning alerts, which is addressed in openshift/cluster-monitoring-operator#2585
=> OCPBUGS-54211: fix issue preventing dev silences from loading

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
1) fixed the issue that happened when user clicks on Silence alert button -> the silence alert form wasn't populated by data
2) did some cleanup and removed unused stuff from the file
=> RHINENG-16773: fixed silence alerts data form not filled with alert details

web/src/components/metrics.tsx
This PR looks to clear out zombie queries from the store when loading queries from the URL in the query browser.
https://github.com/user-attachments/assets/01f241f5-34bd-443c-a97a-7acd3ef60547
=> OU-752: Clear out old queries when loading queries from URL

web/src/components/alerting/AlertList/AggregateAlertTableRow.tsx, web/src/components/alerting/AlertList/hooks/utils.ts
The aggregated alert row was showing filtered states 
In the example `VMCannotBeEvicted`
**DEMO BEFORE**
Silenced state is there even tho we filtered by state firing 
**DEMO AFTER**
https://github.com/user-attachments/assets/5df643eb-fced-4422-a8c7-43ecf1951b53
=> OU-703: fix states filter in aggregated row

web/src/components/alerting/SilencesPage.tsx, web/src/components/alerting/SilencesUtils.tsx
This PR look to give the acm silences page a column width for the cluster column so it shows up.
=> OU-757: Show cluster column heading on acm silences page

web/src/components/alerting/AlertsPage.tsx, web/src/components/alerting/SilencesPage.tsx
Re-add label typeahead to the filters by only aggregating the alerts after the filtering has been done so that the labels on the individual alerts are available to be filtered on.
https://github.com/user-attachments/assets/fab156e8-5494-4c3b-a6c6-16264a16bed1
This PR also looks to add cluster name truncation after 50 characters to prevent dialog sprawl across the page.
=> OU-729,OU-723: Add label typeahead

web/src/components/alerting/AlertDetail/SilencedByTable.tsx, web/src/components/alerting/SilencesUtils.tsx, web/src/components/labels.tsx, web/src/components/metrics.tsx
There were 3 changes requested from UX after our [PF-6](https://issues.redhat.com//browse/PF-6) upgrade:
1. Add spacing around the silences matchers
2. Use a monospace font on the metrics table
3. Place the "clear filters" button on the same line as the filters.
After reviewing Patternfly components, these filters fell under the "toolbar" umbrella, which places the filters on a separate line, so this change wasn't needed. 
https://www.patternfly.org/components/toolbar#with-filters
=> OU-760: Requests UX changes post PF-6

web/src/components/metrics.tsx
This PR looks to fix the column headings on the metrics page such that the full titles are shown.
Before:
After:
=> OCPBUGS-54292: Show column headings on metrics page

web/src/components/metrics/promql-expression-input.tsx
This PR looks to update the metrics typeahead dropdown to look [PF-6](https://issues.redhat.com//browse/PF-6) native
https://github.com/user-attachments/assets/9e13def7-94c2-4140-91c1-adfb7ce28d70
=> OU-750: update the metrics typeahead to look pf-6 native

web/src/components/alerting/AlertsPage.tsx
This PR looks to recover from a regression of a previous bug. It adds back a type so that the filter is able to be used, and then also allows for all items to be matched when no filters are set. 
https://github.com/user-attachments/assets/49092fb3-65e7-4b9b-805f-fe52d87fc1fe
=> OU-767: Allow filtering by cluster name

web/src/components/alerting/AlertsPage.tsx, web/src/components/alerting/SilencesPage.tsx
This PR looks to provide guards on alerts and silences which prevent breaking pages when the cluster label or matcher doesn't exist
=> OU-765: Don't break if cluster doesn't exist

web/src/components/console/utils/single-typeahead-dropdown.tsx, web/src/components/dashboards/shared/dashboard-dropdown.tsx
This PR looks to fix an issue which caused the new variables to be appended onto the old variable values. 
The SingleTypeaheadDropdown is currently used in 3 places: 
- DashboardDropdown
- LegacyVariableDropdown
- VariableDropdown (Perses)
All three of theses locations want the new values to replace the old ones whenever new data is found, so the `clearOnNewItems` has been set to default to true
https://github.com/user-attachments/assets/330cce6b-9543-46ee-bed3-b94d4665c701
=> OCPBUGS-48533: Reset variables when making orthongonal selections

web/src/components/Incidents/IncidentsPage.jsx
We don't need to pass category to the onDeleteGroupIncidentFilterChip, it was causing issues, so I removed it
=> RHINENG-10537: fixed broken delete chip group for incidents filters

web/src/components/MetricsPage.tsx
This PR looks to fix an issue causing columns to be right aligned. This was triggered by the usage of the `<Th modifier="fitContent">` parameter which was added to fix [OCPBUGS-54292](https://issues.redhat.com/browse/OCPBUGS-54292).
We swap to using the `nowrap` which shows the full column title and prevents the right alignment.
Additionally this PR binds the table to the page size, placing a horizontal scroll bar around only the table when neccessary.
https://github.com/user-attachments/assets/ebe09fce-3339-4fdb-8299-78ce2ee4afd0
=> OU-774: bound table scroll and column alignment

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
Add a missing alert name field to labels, so it would populate the alert name field when the user clicks on a "silence alert" button.
=> OU-712: fix: add missing alertname field to silence alert

web/src/components/alerting/SilenceForm.tsx
see [OCPBUGS-56095](https://issues.redhat.com/browse/OCPBUGS-56095)
"Negative matcher" is checked by default on Create silence page
this PR changes isEqual default value from false to true
before the fix(4.19/4.20 builds), "Negative matcher" is checked by default on Create silence page, see
after fix, "Negative matcher" is not checked by default on Create silence page, see
=> OCPBUGS-56095: "Negative matcher" is checked by default on Create silence page

web/src/components/alerting/AlertList/DownloadCSVButton.tsx, web/src/components/alerting/AlertsPage.tsx
https://issues.redhat.com/browse/OU-829
This is a backport of fixes resolved in the main branch. 
- ACM Alerting filtering 
- Add 'Export as CSV'
- Copy/Paste Changes from main branch > AlertsPage, which has already fixed these issues for 4.19. 
- Adjust for Patternfly 5 (HTML is slightly different to accommodate Patternfly 5 instead of Patternfly 6). Business logic should be the same as [main branch > AlertsPage](https://github.com/openshift/monitoring-plugin/blob/main/web/src/components/alerting/AlertsPage.tsx) (as of May 30).
=> OU-829: fix ACM filtering and 'Export as CSV' link

scripts/build-image.sh, web/package-lock.json, web/package.json
Notistack v2 has a peer dependency of material ui V5, the current perses components depend on material UI 6. From notistack v3 this dependency was removed. Overwriting the dependency does not cause issues as the API is compatible.
=> OU-842: fix: override notistack dependency to avoid conflict

web/src/components/console/console-shared/src/components/loading/Loading.tsx, web/src/components/dashboards/perses/PersesWrapper.tsx, web/src/components/dashboards/perses/dashboard-page.tsx
This PR:
- uses the spinner (PF6) instead of the 3 dots as loading indicator
- moves the project dropdown outside the perses wrapper to avoid re-rendering when selecting a new project.
https://github.com/user-attachments/assets/58262464-7f34-4f14-947b-dd2fd6577ac4
=> NO-JIRA: feat: improve loading state and project dropdown re-rendering

web/src/components/alerting/AlertsDetailsPage.tsx
This PR looks to prevent the troubleshooting panel links from appearing on the alert detail page for the non-admin perspective
=> OU-772: remove troubleshooting panel links from non-admin

web/console-extensions.json, web/src/components/alerting/AlertRulesDetailsPage.tsx, web/src/components/alerting/AlertRulesPage.tsx, web/src/components/hooks/usePerspective.tsx
This PR adds the alerting rule tab to the dev console, to allow filtering of "Not Firing" alerts, which in principle are alerting rules.
=> OCPBUGS-55455: feat: add alerting rules tab to dev console

web/cypress/e2e/incidents/00.coo_incidents_e2e.cy.ts, web/cypress/e2e/incidents/01.incidents.cy.ts, web/cypress/fixtures/incidents/pod_crash_loop.yaml, web/cypress/fixtures/incidents/prometheus_rule_pod_crash_loop.yaml, web/cypress/support/commands.ts, web/cypress/support/index.ts, web/cypress/tsconfig.json, web/cypress/views/incidents-page.ts
**Draft PR: Incident Detection E2E Tests Refactor and Expansion**
This Pull Request introduces initial UI tests for the incident detection feature. Its primary purpose is to serve as a proof of concept, a basic smoke test, and to demonstrate the capabilities for incident page interaction within the testing framework.
* **Initial Incident Detection E2E Tests**
* `views/incidents-page.ts` includes **Cypher selectors**, which facilitate operations on the incident page elements.
* `e2e/incidents/01.incidents.cy.ts` incorporates tests designed to verify the setup of the incidents plugin and to interact with the various elements present on the page. This test is dependent on existing alerts to be present in the system at the moment.
* `e2e/incidents/00.incidents.cy.ts` is truly e2e test withou …
=> OBSINTA-776: Incident detection tests

web/src/actions/observe.ts, web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx, web/src/components/Incidents/IncidentsPage.tsx, web/src/components/Incidents/ToolbarItemFilter.tsx, web/src/components/Incidents/incidents-styles.css, web/src/components/Incidents/model.ts, web/src/components/Incidents/utils.ts, web/src/reducers/observe.ts
Mocks:
https://issues.redhat.com/browse/RHINENG-20424
Incident ID is a filter for the group_id parameter of the Incidents
1) Added groupId to the incidentActiveFilters in state management, now it works the same way as state/severity filters
2) Added a filter for incident ID, which is populated with Incident IDs
3) Updated the IncidentsChart component to make it work with the new incidentsActiveFilters.groupId, removed state management parts for the old groupId
4) I removed the logic for the opacity change in the Incidents chart; now, we hide other bars when we filter by Incident.
5) Added a function onFilterToggle for toggling the expansion of filters 
6) Added necessary logic for updating the URL params, clearing the filters by single deletion or group deletion
7) Clear all filters now, …
=> RHINENG-20424: Incident ID filter for the Incidents Page

web/src/components/Incidents/IncidentsPage.tsx, web/src/components/Incidents/ToolbarItemFilter.tsx
Now, when you delete a filter label by clicking on a label/label group, both Alerts Chart and Table are going to show zero state
=> RHINENG-20424: fix clear filter bug with incident selected

web/cypress/fixtures/cmo/update-monitoring-plugin-image.sh
Original script was not working locally when running full test suite was run. 
It was not noticed before due to only few scripts created at the time it was tested and how fast it run. It was noticed that, now that we have more scripts running, during the execution the Cluster Monitoring Operator's CSV was reconciled/reverted to the original content, making some scripts failing in the middle of the execution, not finding some data-test IDs created and not yet merged to main. 
Other point is that, when running in prowJob, the cluster is provisioned with monitoring-plugin image already included. So, even if this script was run during the automation execution, it didn't make any difference, once the original monitoring-plugin image was already the image built with the latest changes.
With …
=> NO-JIRA: automation - fix monitoring-plugin injection

web/src/components/Incidents/IncidentsPage.tsx
This updates/fixes the incident metric name. This PR depends on https://github.com/openshift/cluster-health-analyzer/pull/50 and should be merged after.
=> OBSINTA-463: Rename the cluster health metrics

web/src/components/Incidents/AlertsChart/AlertsChart.tsx, web/src/components/Incidents/ToolbarItemFilter.tsx, web/src/components/Incidents/model.ts, web/src/components/Incidents/utils.ts, web/src/store/store.ts
1. I broke the alerts chart after merging fresh main into my development branch, so I am fixing it with this PR.
2. During the migration/changes to the state management system, the person who made the changes missed that we used a different structure for storing Incident filters, and used the old version. I had to restore that back and update the code, types, and store format.
=> OU-833: fix 2 bugs for incidents page

web/cypress/support/commands/auth-commands.ts
The no-session login did not run the validation code, which lead to not closing the openshift guide. This commit wraps the validation login into a cypress command and runs it also with the no-session login.
=> NO-JIRA: Login validation for all session flows

web/cypress.config.ts, web/cypress/README.md, web/cypress/configure-env.sh, web/cypress/e2e/incidents/00.coo_incidents_e2e.cy.ts, web/cypress/e2e/incidents/01.incidents.cy.ts, web/cypress/fixtures/export.sh, web/cypress/support/incidents_prometheus_query_mocks/README.md, web/cypress/support/incidents_prometheus_query_mocks/mock-generators.ts, web/cypress/support/incidents_prometheus_query_mocks/prometheus-mocks.ts, web/cypress/views/incidents-page.ts
The UI changes introduced few quirks that break the traversal of incidents, but also solved some that had existing  workarounds in the testsuite.
This commit removes the retry for the not loading alerts chart, as it is loading reliably now, but because stale state is loaded first, it introduces hard coded wait time.
https://issues.redhat.com/browse/OU-1016 is the issue that this workaround is about. If it will be fixed, the workaround is to be replaced and the incident traversal will serve as a regression test for it.
Additionally, it fixes the failing traversal when no incidents exits in the UI and adds test case that verifies that on mocked data.
Depends on #553 so it is possible to test it with current setup  (mocking and request transformation due to old new metric), but the changes …
=> OBSINTA-858: Cypress incidents incident traversing robustness

web/cypress/README.md, web/cypress/configure-env.sh, web/cypress/fixtures/export.sh, web/cypress/support/commands/operator-commands.ts
In local setup, I run the testsuite against cluster without the COO installed. This variable skips not only COO installation, but also the verification and the setup of the UI monitoring plugin.
Additionally, it refactors the aboutModal and getPodInfo calls to be skipped when CYPRESS_DEBUG is not true and moves them inside the sessions.
=>  OBSINTA-857: Cypress add SKIP_ALL_INSTALL

web/src/components/Incidents/AlertsChart/AlertsChart.tsx, web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx, web/src/components/Incidents/IncidentsTooltip.tsx, web/src/components/Incidents/utils.ts
The `height` parameter was not the tooltip height (probably it was the whole chart height), so the vertical position computation was wrong. 
The height is now estimated based on the number of text lines in the tooltip.
=> NO-JIRA: Fix tooltip vertical position

web/src/components/Incidents/api.ts, web/src/components/utils.ts
Fixes JSON parsing error that occurred when removing incident filters.
The buildPrometheusUrl function now returns null for empty queries
instead of an empty string, preventing invalid API calls to the root
URL which returned HTML instead of expected JSON data.
Assisted-By: Claude Code
=> NO-JIRA:  fix handle empty queries when removing incident filters
