openshift/monitoring-plugin

package.json

Also fixes `consolePlugin.name` in package.json

Set initial version number to 1.0.0

---

README.md
charts/openshift-console-plugin/.helmignore
charts/openshift-console-plugin/Chart.yaml
charts/openshift-console-plugin/templates/_helpers.tpl
charts/openshift-console-plugin/templates/configmap.yaml
charts/openshift-console-plugin/templates/consoleplugin.yaml
charts/openshift-console-plugin/templates/deployment.yaml
charts/openshift-console-plugin/templates/service.yaml
charts/openshift-console-plugin/templates/serviceaccount.yaml
charts/openshift-console-plugin/values.yaml
ct.yaml

Helm charts are taken from github.com/openshift/console-plugin-template

Add Helm charts for installing plugin

---

package.json

Updated to be consistent with text used in README.

Update text descriptions in package.json

---

Dockerfile.art

Ref. https://issues.redhat.com/browse/ART-6050

Add Dockerfile for ART builds

---

src/components/alerting.tsx

Use `Promise.allSettled` instead of `Promise.all` to better handle the case where some of the requests fail and some succeed.

For silences bulk expire, handle case where some fail and some succeed

---

locales/en/public.json
src/components/metrics.tsx

Copy change https://github.com/openshift/console/pull/12621 to plugin

Copy console PR #12621 to plugin

---

src/components/silence-form.tsx

Copy https://github.com/openshift/console/pull/12577 to plugin

Copy console PR #12577 to plugin

---

src/components/_monitoring.scss
src/components/console/utils/headings.tsx
src/components/silence-form.tsx

This component is not available in the plugin SDK, so refactor to use PatternFly components instead.

Refactor away PageHeading

---

src/components/alerting.tsx

Copy https://github.com/openshift/console/pull/12592 to plugin

Copy console PR #12592 to plugin

---

src/components/targets.tsx

Copy monitoring UI code changes from https://github.com/openshift/console/pull/12861 to plugin

Copy web console PR #12861 changes to plugin

---

src/components/alerting.tsx
src/components/console/extensions/alerts.ts
src/components/console/extensions/dashboard-data-source.ts
src/components/console/extensions/types.ts
src/components/fetch-alerts.tsx
src/components/types.ts
src/components/utils.ts

Copy monitoring UI code changes from the following two PRs to plugin
- https://github.com/openshift/console/pull/12436 (main PR)
- https://github.com/openshift/console/pull/12632 (follow up to main PR)
Also upgrade the web console dynamic plugin SDK packages to their latest versions.

OCPBUGS-15324: Copy web console PRs #12436 and #12632 changes to plugin

---

src/components/_monitoring.scss

| Before | After |
| - | - |
| ![before](https://github.com/openshift/monitoring-plugin/assets/460802/5c0969ed-0811-4942-b9fb-1396ad518a89) | ![after](https://github.com/openshift/monitoring-plugin/assets/460802/8fd9f93e-e5eb-4281-ae89-9c69b4581cff) |

OU-191: Fix width of dashboards tables to use full panel width

---

src/components/dashboards/index.tsx

**Related Issue**: 
[OCPBUGS-15323](https://issues.redhat.com/browse/OCPBUGS-15323)
**Summary**: 
Fix custom dashboard logic to await extension resolution before using the extension. This is needed because of the update to use `useResolvedExtensions()` instead of `useExtension()` from the `openshift-console/dynamic-plugin-sdk`.

OCPBUGS-15323: Use datasource defined in dashboard definition broken by switch to web console monitoring plugin

---

Dockerfile.local

This is the same as Dockerfile except it assumes that Nginx is setup using the default config.

OU-311: Add Dockerfile for local testing

---

src/components/alerting.tsx

**Description** 
This PR creates an extension point in the kebab menu on the alerts page. 
**Screenshots**
_Figure 1._ The screenshot above shows new kebab items representing actions received from the mocked extension.

OU-310: Add an extension point for alerts, to be able to add an inspect link

---

locales/en/plugin__monitoring-plugin.json
src/components/metrics.tsx

Add the ability to export data to a .csv file.

OU-236: Add CSV export option to dashboards and metrics tables

---

README.md

Update README with local development instructions.

NO-ISSUE: Update README.md

---

locales/en/plugin__monitoring-plugin.json
src/components/_monitoring.scss
src/components/metrics.tsx

On the metrics page, add a predefined queries dropdown.

OU-439: Add the predefined queries list to the admin metrics 

---

src/components/Incidents/AlertsChart/AlertsChart.css
src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/AlertsChart/IncidentsChartLegend.jsx
src/components/Incidents/IncidentsChart/IncidentsChart.css
src/components/Incidents/IncidentsChart/IncidentsChart.jsx
src/components/Incidents/IncidentsChart/IncidentsChartLegend.jsx
src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
src/components/Incidents/IncidentsPage.jsx

RHINENG-10908: add more flex and chartlegend

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsChart/IncidentsChart.jsx
src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/_monitoring.scss

Removed promises fetch and changed it to an easier-to-read async await.
Added data processing that waits for data to be fetched then changes data into format of HH/DD/MM/YY

refactored fetch connected it to data processing

---

package.json
src/components/console/graphs/bar.tsx
src/components/query-browser-theme.ts
yarn.lock

updated patternfly react charts to solve bugs

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js

1. Removed a bunch of unnecessary code, now it is cleaner and easier to understand
2. Updated fetch function: now it collects the data depending on the number of days requested and sets it into state
3. Added functions to combine data, dedupe it and prepare it to be consumed by chart

Improved fetch and data preparation for charts

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js

Data is pulled from the API and mapped onto the chart. next step is to adjust dates according to the API request range

data from the api mapped onto chart

---

web/console-extensions.json

Reverts openshift/monitoring-plugin#173

Revert "OU-259: Update console-extension to use translations in plugin__monitoring-plugin"

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js

Depending on the value of defaultTimespan = parsePrometheusDuration('7d') we make a request for the correct amount of days to the prometheus database and then create a correct amount of day "strokes" in chart and name them accordingly
In the future this value will come from a filter in the Page component that will manipulate both chart and table below the chart

dates to chart automation

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsChart/IncidentsChart.jsx
src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js

I added an incidents chart functionality
1. Removed old parts of components that were made before migration to patternfly
2. New fetch for Prometheus database to fetch the incident data
3. Utils functions that allow us to create chart bars and make timestamps
4. Make bars for the chart and populate the chart with bars

incident chart functionality part1

---

package.json
src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsChart/IncidentsChart.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js
yarn.lock

1. Added 2 filters above the charts
2. Implemented date range filter functionality. Depending on the chosen date range we adjust the graphs and fetch the data for both incidents and alerts
3. Still working on the other filter
4. Removed unused pieces of code, cleaned up functions, and added 1 utils function
5. Adjusted chart tooltip component - incidents ID is too long and was breaking the frame of the tooltip.

Incidents filters

---

src/components/Incidents/utils.js

After this utils update chart shows the correct severity if the severity changes over time 
based on the https://github.com/iNecas/cluster-health-analyzer/blob/docs/docs/design.md#the-normalized-severity-value
Also, Ivan Necas told me that an alert/incident with the "Watchdog" name is not really an alert and I can filter it out so I added filters to the utils function to remove these alerts/incidents

severity utils update to show severity changes overtime

---

src/components/Incidents/utils.js

I added jsdoc for 2 functions so I could have highlights that describes them + it will be easier to write tests for them in the future

add jsdoc for 2 utils funcitons

---

src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/utils.js

Added functionality for filters 
I may need to fix things in the future when real incident data is present in the Prometheus database.
I added a JSdoc for the filter function, I found it much more useful than any typescript interfaces and other stuff, because it provides highlights and allows you to explain how the function works + provide an example

RHINENG-12334: filters for incidents

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsChart/IncidentsChart.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/IncidentsTableRow.jsx
src/components/Incidents/api.js
src/components/Incidents/consts.js
src/components/Incidents/utils.js

I did the following things in this PR:
1. Added basic VirtualizedTable component, I will continue working with it in the next PRs. The reason for that is that I had to update the Alerts API request to combine/merge data on incidents and alerts.
2. Separated query-generating functions into api.js file. I want to leave utils.js for smaller functions unrelated to the API.
3. Added a function collectIncidentsDataForApiQuery, which collects the data of the incident and creates an array of objects with values.
4. Output of collectIncidentsDataForApiQuery is used in the createAlertsQuery function. This function is responsible for mapping over the input and creating API queries for the Alerts endpoint. The reason is the following: Ivan told me that some of the incidents could be missing …

feat(RHINENG-10902): Incidents table implementation

---

README.md

NO-JIRA: Update log-level docs in monitoring-plugin

---

src/components/Incidents/utils.js

https://issues.redhat.com/browse/RHINENG-10537
I updated the logic of how we generate bars in charts. From now on instead of generating 1 small section/bar per each hour that an incident/alert is firing, we calculate the whole length of the firing and the changes in severity. Then we generate arrays with timestamps and create bars for each array. 
It fixes several things:
1) visually they look like mocks
2) dates of "start firing" and "end firing" are correct
3)its easier to click on the incident and trigger a fetch
4)performance is improved

RHINENG-10537: update chart generating logic for rows

---

src/components/Incidents/AlertsChart/AlertsChart.jsx
src/components/Incidents/IncidentsTable.jsx

empty states for chart and table

---

src/components/Incidents/IncidentsDetailsRowTable.jsx
src/components/Incidents/IncidentsPage.jsx
src/components/Incidents/IncidentsTable.jsx

Implemented the links in the expanded details table. now they work the same way as in Alerts page

fixed links in expanded details table

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/console/graphs/bar.tsx
web/src/components/query-browser-theme.ts

https://issues.redhat.com/browse/RHINENG-10904
I added 2 kebab actions to copy the user experience from the Alerting page.

RHINENG-10904: Kebab actions for expanded details

---

web/src/components/Incidents/utils.js

Incidents chart fixed double tooltip bug

---

web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/consts.js
web/src/components/Incidents/utils.js

https://issues.redhat.com/browse/RHINENG-10907
1) removed openshift filter
2) added toolbar filter + dropdown
3) connected all of the filters to the state management and data processing
4) added hide graph button that hides it

RHINENG-10907: Filter to toolbar refactor

---

web/console-extensions.json

navigation isnt open for incidents fix

---

web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/api.js

Made fetch for incidents nav DRYer

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx

For some reason the links broke, so I cleaned up and updated the code

Incidents expanded details: fixed broken links bug

---

web/src/actions/observe.ts
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/consts.js
web/src/components/Incidents/utils.js
web/src/reducers/observe.ts

1) I added redux states for initial state and active filters
2) I added functions that update URL based on change in active filters in redux
3) When user opens the page for the first time and there are no URL params present - we load the initial state filters
4) When user opens the page with URL params present - we update the active filters accordingly and fetch + filter data based on that
5) I updated the onSelect functions and other functions and moved some of the outside of the Incident Page component and into utils.js
https://issues.redhat.com/browse/RHINENG-10906

RHINENG-10906: Filters to url params

---

web/src/actions/observe.ts
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsHeader/IncidentsHeader.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/IncidentsTable.jsx
web/src/reducers/observe.ts

Refactored some of useState management to redux

NO-JIRA: Refactor usestates to redux

---

web/package-lock.json
web/package.json

This PR updates cross-spawn vulnerable dependency

OCPBUGS-44391: fix cross-spawn vulnerable dependency

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/IncidentsTable.jsx
web/src/components/Incidents/api.js

This should fix the issue that caused request to prometheus-tenancy endpoint instead of regular endpoint

NO-JIRA: updated api request to remove prom tenancy issue

---

web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/processIncidents.ts

This should fix issue with only 1 alert presented when user click on incident

NO-JIRA: only 1 alert in table fix

---

web/src/components/Incidents/AlertsChart/AlertsChart.jsx
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx

https://issues.redhat.com/browse/RHINENG-14524
A small improvement that makes the chart height adjust automatically depending on the number of rows.
Values could be adjusted later after reviews and QA
Also I updated the charts tooltip because this one is less buggy and doesn't cover the bars

RHINENG-14524: incidents charts update cursor and 

---

web/package.json
web/yarn.lock

OCPBUGS-44394: remove unused package and upgrade vulnerable dependency

---

Makefile
README.md
cmd/plugin-backend.go
config/dev-config.patch.json
pkg/plugin_handler.go
pkg/server.go
scripts/start-console.sh

This PR adds better DX for running the monitoring-plugin with features enabled while developing.
This doesn't exactly add hot reloading, but the page does refresh when changes are made to the frontend

NO-JIRA: Fix feature flagged DX

---

web/src/components/Incidents/IncidentsPage.jsx

NO-JIRA: fix incidents filter width

---

package.json
yarn.lock

OCPBUGS-44395: remove unused package and upgrade vulnerable dependency

---

web/src/components/Incidents/processIncidents.ts

Fixed filters not working. You can find recordings of the filters fix in the ticket below
https://issues.redhat.com/browse/RHINENG-14677

RHINENG-14677: fix filters for incidents

---

web/src/components/Incidents/processAlerts.js

https://issues.redhat.com/browse/RHINENG-14585

RHINENG-14585: Remove pending alerts from processing and add another value to the unique key

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/Incidents/incidents-styles.css

Now the kebab actions are disabled if there is no rule for this alert
Plus I added a small margin to the text in the table so they would not stick to the icons.

RHINENG-14523: (fix) update expanded details

---

web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/consts.js
web/src/components/Incidents/processIncidents.ts
web/src/components/Incidents/utils.js
web/src/reducers/observe.ts

https://issues.redhat.com/browse/RHINENG-14555
added more filters.
'Recent' (everything that is not older than 7 days.
'Persistent' (everything that started more than 7 days ago).
Informative, Warning, Critical - self-explanatory.
Resolved - if the last timestamp is older than 10 minutes - it is resolved.
Firing - If the last timestamp is younger than 10 minutes - it is firing.
Connected filters to redux store
Updated function for filtering

RHINENG-14555: Update for the filters and default state for the filters

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/_monitoring.scss
web/src/components/alerting.tsx
web/src/components/alerting/AlertsPage.tsx
web/src/components/alerting/SilencesDetailPage.tsx
web/src/components/console/utils/single-typeahead-dropdown.tsx
web/src/components/dashboards/index.tsx
web/src/components/kebab-dropdown.tsx
web/src/components/metrics.tsx
web/src/components/query-browser.tsx
web/src/components/silence-form.tsx

https://issues.redhat.com/browse/OU-499
port from
- https://github.com/openshift/console/pull/14138
- https://github.com/openshift/console/pull/14247
- https://github.com/openshift/console/pull/14157
Also migrated `KebabDropdown`:
https://github.com/user-attachments/assets/23da9ba0-089d-4a33-8a55-df2f7ae31f86
What changed:
- Metrics:
- Timespan dropdown ![image](https://github.com/user-attachments/assets/8eb4cc51-fc5c-48b5-ad2d-d788bded152f)
- All kebab menus ![image](https://github.com/user-attachments/assets/14a88801-035c-4ba2-b37c-e311848733db)
- Monitoring Dashboard:
- Dashboard selector ![image](https://github.com/user-attachments/assets/58f4ca80-603a-4211-a82d-6a6de57e449a)
- All kebab menus ![image](https://github.com/user-attachments/assets/14bc0c13-fb72-4849-b570-1ca17f34bc6d)
- …

OU-499: Port CONSOLE-4124, ODC-7655, CONSOLE-4127 to dynamic plugin

---

web/src/components/Incidents/IncidentsPage.jsx

Change text of the hide/show button depending on the state. If graphs are hidden then its "Show graph"

RHINENG-15115: update hideshow graph button

---

web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/Incidents/utils.js

Fixed dates inconsistency on Incidents Page

RHINENG-15114: incidents page fixed date style inconsistency

---

config/incidents.patch.json
scripts/start-console.sh
web/src/components/alerting.tsx
web/src/components/hooks/useFeatures.ts
web/src/components/hooks/usePerspective.tsx

Reverts openshift/monitoring-plugin#303

Revert "OU-588: Move Incidents Tab to Alerting Page "

---

README.md
config/clear-extensions.patch.json
config/dev-config.patch.json
web/console-extensions.json
web/src/actions/observe.ts
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/IncidentsTable.jsx
web/src/components/alerting.tsx
web/src/components/alerting/AlertsDetailPage.tsx
web/src/components/alerting/AlertsPage.tsx
web/src/components/alerting/SilencesDetailPage.tsx
web/src/components/alerting/SilencesPage.tsx
web/src/components/dashboards/custom-time-range-modal.tsx
web/src/components/dashboards/graph.tsx
web/src/components/dashboards/index.tsx
web/src/components/dashboards/timespan-dropdown.tsx
web/src/components/hooks/usePerspective.tsx
web/src/components/metrics.tsx
web/src/components/query-browser.tsx
web/src/components/silence-form.tsx
web/src/components/targets.tsx
web/src/reducers/observe.ts

This change adds a new redux reducer which is exclusive to the monitoring-plugin, as well as the extension points needed for the virtualization perspective.

OU-630: Add Needed Virtualization Perspective Changes

---

README.md
config/clear-extensions.patch.json
web/console-extensions.json
web/src/actions/observe.ts
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/IncidentsTable.jsx
web/src/components/alerting.tsx
web/src/components/alerting/AlertsDetailPage.tsx
web/src/components/alerting/AlertsPage.tsx
web/src/components/alerting/SilencesDetailPage.tsx
web/src/components/alerting/SilencesPage.tsx
web/src/components/dashboards/custom-time-range-modal.tsx
web/src/components/dashboards/graph.tsx
web/src/components/dashboards/index.tsx
web/src/components/dashboards/timespan-dropdown.tsx
web/src/components/hooks/usePerspective.tsx
web/src/components/metrics.tsx
web/src/components/query-browser.tsx
web/src/components/silence-form.tsx
web/src/components/targets.tsx
web/src/reducers/observe.ts

[release-4.18] OU-633: Add Needed Virtualization Changed

---

web/src/components/Incidents/utils.js

updated logic for organizing intervals of the same severity for the bar chart generation

RHINENG-15190: fix gap in incident charts

---

web/src/components/Incidents/IncidentsPage.jsx

After some discussions with PM's we came up with a decision to revert this change

NO-JIRA: revert reset all filters button

---

web/src/actions/observe.ts
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/consts.js
web/src/components/Incidents/processIncidents.ts
web/src/components/Incidents/utils.js
web/src/reducers/observe.ts

1) Added redux state for filtered data (will be used in syncing states)
2) Removed recent filter and renamed persistent back to long standing (why oh god why)
3) Updated filters logic according to the ticket description
4) SYNC (in PROGRESS!!!)
https://issues.redhat.com/browse/RHINENG-15501

RHINENG-15501: Improve incidents filter logic and sync

---

web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx

during one of the rebases/merges I lost a return of the function that regulate color for incidents chart
fixing it here

NO-JIRA: fixed function for incident chart colors

---

web/src/components/Incidents/utils.js

Alberto requested a change in long standing filter
https://issues.redhat.com/browse/OU-635?focusedId=26446030&page=com.atlassian.jira.plugin.system.issuetabpanels%3Acomment-tabpanel#comment-26446030

RHINENG-15501: hotfix because filter requirement were updated

---

web/src/components/Incidents/AlertsChart/AlertsChart.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/utils.js

1) added '---' to the chart tooltip in case if alert is firing
2) fixed the toggle for the day's filter, it was getting stuck in the expanded state.

NO-JIRA: Incidents page small fixes

---

web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/consts.js
web/src/components/Incidents/utils.js

https://issues.redhat.com/browse/RHINENG-10537
Removed setter for loading state from the filter -> it was forcing the table into an incorrect state when the user selected the same days that were already chosen in the filter

RHINENG-10537: fix incidents page loading state issue

---

web/src/components/Incidents/AlertsChart/AlertsChart.jsx
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsDetailsRowTable.jsx
web/src/components/Incidents/utils.js

https://issues.redhat.com/browse/RHINENG-10537
1. Refactored big function that was responsible for creating intervals/detecting/transitions/gaps and much more for the Incidents chart. Now it has several functions, and it's easier to read. They all have JSdoc so they are easier to understand
2. Refactored big function that was responsible for creating intervals/detecting gaps and much more for the Alerts chart.
3. Added 'nodata' values to 'gaps' and 'empty intervals in the chart. Now the tooltip won't appear if you hover over empty space in the chart. It is done both for the Incidents and Alerts chart. 
4. Different type of tooltip container is used for both the incidents and Alerts charts, it work better overall.
5. Small naming changes

RHINENG-10537:Voronoi container review branch

---

web/src/components/TypeaheadSelect.tsx
web/src/components/alerting/SilencesDetailPage.tsx
web/src/components/alerting/SilencesUtils.tsx
web/src/components/metrics.tsx

This PR removes deprecated components and replaces them with the current versions

OU-499: remove deprecated components

---

web/package-lock.json
web/package.json

This PR adds the material ui dependency so it can be fetched by cachito for hermetic builds

COO-684: add mui/material as is required as peer dependency

---

web/src/components/console/utils/poll-hook.ts
web/src/components/dashboards/legacy/useLegacyDashboards.ts
web/src/components/query-browser.tsx

This allows to set the auto refresh to off. Taken from the pf6 changes to be able to backport it.

OU-678: fix: allow to set refresh interval to off

---

web/src/components/alerting/AlertList/DownloadCSVButton.tsx
web/src/components/alerting/AlertsPage.tsx

**Demo**
**CSV example**
[openshift (8).csv](https://github.com/user-attachments/files/19794961/openshift.8.csv)

OU-702: re-add csv button for aggregated alert list

---

web/src/components/Incidents/AlertsChart/AlertsChart.jsx
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsPage.jsx

1. Add memoization for parse url params function because it was called too often.
2. Wrapped chart data calculations in memoization to avoid recalculations if the values are the same
3. Wrapped getOpacity and isHidden in useCallback to reduce the number of rerenders

NO-JIRA: fix(incidents): performance improvements for incidents page

---

web/src/actions/observe.ts
web/src/components/Incidents/AlertsChart/AlertsChart.jsx
web/src/components/Incidents/IncidentsChart/IncidentsChart.jsx
web/src/components/Incidents/IncidentsPage.jsx
web/src/components/Incidents/utils.ts
web/src/reducers/observe.ts

https://issues.redhat.com/browse/RHINENG-17675
1. Now clicking on the incident will add it to the URL parameters, clicking on the incident again it will remove it from the url.
2. You can copy the URL with groupId added and open it in the new tab, that will load the page with incident selected, alerts chart filled and table populated.

RHINENG-17675: feat: add group id to url params

---

OWNERS

preparation to onboard cypress automation testing files

NO-JIRA: chore: Update OWNERS

---

web/src/components/query-browser.scss

Fixes: [OU-744](https://issues.redhat.com/browse/OU-744)

OU-744: fix: set correct pf color for gradient background on legacy dashboards legend

---

web/src/components/MetricsPage.tsx

https://github.com/user-attachments/assets/70fb34a3-94f5-4f01-8642-69abea1de965

OU-943: remove broken useEffect

---

web/cypress/e2e/regression/01.reg_alerts.cy.ts
web/cypress/views/details-page.ts

- scripts passed locally but failed in the pipeline
- small adjustments

NO-JIRA: automation failed in the periodic job

---

web/console-extensions.json
web/src/components/alerting.tsx
web/src/components/hooks/usePerspective.tsx

OCPBUGS-60199: feat: add alerting rules tab to dev console

---

web/cypress.config.ts
web/cypress/downloads/openshift.csv
web/cypress/e2e/monitoring/regression/02.reg_metrics.cy.ts
web/cypress/fixtures/monitoring/constants.ts
web/cypress/support/commands.ts
web/cypress/support/index.ts
web/cypress/views/alerting-rule-details-page.ts
web/cypress/views/details-page.ts
web/cypress/views/list-page.ts
web/cypress/views/metrics.ts
web/src/components/MetricsPage.tsx
web/src/components/console/graphs/graph-empty.tsx
web/src/components/data-test.ts
web/src/components/query-browser.tsx

[OU-932](https://issues.redhat.com/browse/OU-932) Observe > Metrics scenario.
To deliver this initial scenario:
- constants.ts was created to start centralizing all strings related to lists (dropdowns, filtering options), inline messages, help texts that will be used in the following tasks
- metrics.ts view with main components, actions and assertions that will be used in the following tasks
- new regression file for metrics
[OU-933](https://issues.redhat.com/browse/OU-933) Observe > Metrics > Actions
[OU-934](https://issues.redhat.com/browse/OU-934) Observe > Metrics > Insert example query
[OU-935](https://issues.redhat.com/browse/OU-935) Observe > Metrics > Add query - Run queries - Kebab icon
[OU-936](https://issues.redhat.com/browse/OU-936) Observe > Metrics > Predefined query > …

OU-932: automation - metrics

---

web/cypress/e2e/coo/01.coo_bvt.cy.ts
web/cypress/e2e/monitoring/01.bvt_monitoring.cy.ts
web/cypress/e2e/monitoring/regression/01.reg_alerts.cy.ts
web/cypress/e2e/monitoring/regression/02.reg_metrics.cy.ts
web/cypress/e2e/monitoring/regression/03.reg_legacy_dashboards.cy.ts
web/cypress/fixtures/coo/perses-dashboard-sample.yaml
web/cypress/fixtures/coo/prometheus-overview-variables.yaml
web/cypress/fixtures/coo/thanos-compact-overview-1var.yaml
web/cypress/fixtures/monitoring/alert.ts
web/cypress/fixtures/monitoring/constants.ts
web/cypress/support/commands/operator-commands.ts
web/cypress/views/alerting-rule-details-page.ts
web/cypress/views/common.ts
web/cypress/views/metrics.ts
web/src/components/data-test.ts

- [OU-897](https://issues.redhat.com/browse/OU-897) - Hide/Show Graph cross Monitoring pages
- [OU-987](https://issues.redhat.com/browse/OU-987) - [QE][Automation][COO-BVT] - workaround due to OCPBUGS-58468 won't be fixed

OU-897: automation OU-721 and hygiene of existing scripts

---

web/src/components/Incidents/AlertsChart/AlertsChart.tsx
web/src/components/Incidents/IncidentsPage.tsx
web/src/components/Incidents/utils.ts

Modified alerts timeline to automatically fit to actual alert data timespan instead of using fixed incidents timeline range, improving readability by focusing on relevant alert activity periods.
Assisted-by: Claude Code (claude-sonnet, claude-3-5-haiku)

OU-783: Fit the alerts timeline to the actual data timespan

---

web/src/components/Incidents/AlertsChart/AlertsChart.tsx
web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
web/src/components/Incidents/IncidentsPage.tsx
web/src/components/Incidents/IncidentsTable.tsx
web/src/components/Incidents/incidents-styles.css
web/src/components/Incidents/utils.ts

OBSINTA-789: Update layout and labels

---

web/console-extensions.json
web/src/components/alerting.tsx

manual cherry pick of https://github.com/openshift/monitoring-plugin/pull/487

OCPBUGS-61891: feat: add alerting rules tab to dev console

---

web/src/components/Incidents/IncidentsPage.tsx

https://issues.redhat.com/browse/RHINENG-20863
Fix the case when the fetch hook is triggered twice, once because the redux store wasn't updated in time from the URL params, and the second time when the redux store was updated with filters from URL params.
1. Combined 2 hooks that were fetching data for ALL incidents and one incident based on group ID into one hook.
2. Added "isInitialized" useState so the fetching would happen after the redux store is updated with filters from URL params

RHINENG-20863: improved fetching logic for incidents

---

web/src/components/Incidents/processAlerts.ts

Reverts openshift/monitoring-plugin#550

OU-1011: REVERT add a 5 minute to the first alert timestamp

---

.gitignore

/web/screenshots: When running using cypress open, screenshots are created here.
/web/cypress/export-env.sh: Output of the config script.

NO-JIRA: Update .gitignore (Cypress specific)

---

web/package-lock.json
web/package.json

Manual cherry pick of https://github.com/openshift/monitoring-plugin/pull/561

COO-1134: [release-coo-0.5] fix: update vulnerable dependencies

---

web/src/components/Incidents/IncidentsChart/IncidentsChart.tsx
web/src/components/Incidents/IncidentsPage.tsx
web/src/components/Incidents/model.ts
web/src/components/Incidents/processAlerts.spec.ts
web/src/components/Incidents/processAlerts.ts
web/src/components/Incidents/processIncidents.spec.ts
web/src/components/Incidents/processIncidents.ts
web/src/components/Incidents/utils.spec.ts
web/src/components/Incidents/utils.ts

I reviewed all incident and alert loading and transformation algorithms to handle edge cases and improve code readability. This critical phase was human-driven. Final refactoring and testing were primarily AI-generated.
- Added 5min padding datapoints to better render the bar charts
- Added unit tests
- Renamed variables, types
- Added comments
Assisted by: Claude (claude-3-5-haiku, claude-sonnet)

OU-1011: Render short-lived incidents and alerts
